<project name="MyArithProject" default="jar" basedir=".">

    <!-- Compile all necessary classes -->
    <target name="compile">
        <javac srcdir="." destdir="." includeantruntime="false">
            <include name="arbitaryarithmetic/AInteger.java"/>
            <include name="arbitaryarithmetic/AFloat.java"/>
            <include name="myInfArith.java"/>
        </javac>
    </target>

    <!-- Create a JAR file from compiled .class files -->
    <target name="jar" depends="compile">
        <jar destfile="myArithLib.jar" basedir=".">
            <include name="arbitaryarithmetic/*.class"/>
            <include name="myInfArith.class"/>
        </jar>
    </target>

    <!-- Clean up all generated .class files and jar file-->
    <target name="clean">
        <!-- Delete all .class files -->
        <delete>
            <fileset dir="." includes="**/*.class"/>
        </delete>
        <!-- Delete the generated JAR file -->
        <delete file="myArithLib.jar"/>
    </target>

    <target name="run" depends="compile">
    <java classname="myInfArith" fork="true">
        <classpath path="."/>
        <arg value="int"/>
        <arg value="add"/>
        <arg value="3.14"/>
        <arg value="2.86"/>
    </java>
</target>


</project>
